export const SKILLS = [
  { id: 'acrobacia', name: 'Acrobacia', attr: 'des', description: 'Usada para equilíbrio, saltos e quedas.' },
  { id: 'adestramento', name: 'Adestramento', attr: 'car', description: 'Usada para lidar com animais e montarias.' },
  { id: 'atletismo', name: 'Atletismo', attr: 'for', description: 'Usada para escalar, nadar e correr.' },
  { id: 'atuacao', name: 'Atuação', attr: 'car', description: 'Usada para artes performáticas e entretenimento.' },
  { id: 'cavalaria', name: 'Cavalaria', attr: 'des', description: 'Usada para combater e realizar manobras montado.' },
  { id: 'conhecimento', name: 'Conhecimento', attr: 'int', description: 'Usada para saber sobre história, geografia e natureza.' },
  { id: 'cura', name: 'Cura', attr: 'sab', description: 'Usada para tratar ferimentos e doenças.' },
  { id: 'diplomacia', name: 'Diplomacia', attr: 'car', description: 'Usada para persuadir e negociar pacificamente.' },
  { id: 'enganacao', name: 'Enganação', attr: 'car', description: 'Usada para mentir, disfarçar-se e ludibriar.' },
  { id: 'fortitude', name: 'Fortitude', attr: 'con', description: 'Sua resistência física contra venenos e cansaço.' },
  { id: 'furtividade', name: 'Furtividade', attr: 'des', description: 'Usada para se esconder e mover-se em silêncio.' },
  { id: 'guerra', name: 'Guerra', attr: 'int', description: 'Usada para táticas, estratégia e conhecimento militar.' },
  { id: 'iniciativa', name: 'Iniciativa', attr: 'des', description: 'Define a ordem de agir em combate.' },
  { id: 'intimidacao', name: 'Intimidação', attr: 'car', description: 'Usada para coagir e assustar outros.' },
  { id: 'intuicao', name: 'Intuição', attr: 'sab', description: 'Usada para perceber mentiras e intenções.' },
  { id: 'investigacao', name: 'Investigação', attr: 'int', description: 'Usada para procurar pistas e analisar cenas.' },
  { id: 'jogatina', name: 'Jogatina', attr: 'car', description: 'Usada para jogos de azar e apostas.' },
  { id: 'ladinagem', name: 'Ladinagem', attr: 'des', description: 'Usada para abrir fechaduras e bater carteiras.' },
  { id: 'luta', name: 'Luta', attr: 'for', description: 'Usada para ataques corpo a corpo.' },
  { id: 'misticismo', name: 'Misticismo', attr: 'int', description: 'Usada para identificar magias e itens mágicos.' },
  { id: 'nobreza', name: 'Nobreza', attr: 'int', description: 'Usada para etiqueta, política e linhagens.' },
  { id: 'oficio', name: 'Ofício', attr: 'int', description: 'Usada para fabricar itens e exercer profissões.' },
  { id: 'percepcao', name: 'Percepção', attr: 'sab', description: 'Usada para notar coisas ao seu redor.' },
  { id: 'pilotagem', name: 'Pilotagem', attr: 'des', description: 'Usada para conduzir veículos e embarcações.' },
  { id: 'pontaria', name: 'Pontaria', attr: 'des', description: 'Usada para ataques à distância.' },
  { id: 'reflexos', name: 'Reflexos', attr: 'des', description: 'Sua agilidade para desviar de perigos.' },
  { id: 'religiao', name: 'Religião', attr: 'sab', description: 'Usada para saber sobre deuses e planos.' },
  { id: 'sobrevivencia', name: 'Sobrevivência', attr: 'sab', description: 'Usada para rastrear e viver nos ermos.' },
  { id: 'vontade', name: 'Vontade', attr: 'sab', description: 'Sua resistência mental e determinação.' }
];
