// src/ui/skillsData.js
export const SKILLS = [
  { id: 'acrobacia', name: 'Acrobacia', attr: 'des', description: 'Equilíbrio e saltos.' },
  { id: 'adestramento', name: 'Adestramento', attr: 'car', description: 'Lidar com animais.' },
  { id: 'atletismo', name: 'Atletismo', attr: 'for', description: 'Escalar, nadar e correr.' },
  { id: 'atuacao', name: 'Atuação', attr: 'car', description: 'Arte e entretenimento.' },
  { id: 'cavalaria', name: 'Cavalaria', attr: 'des', description: 'Montaria em combate.' },
  { id: 'conhecimento', name: 'Conhecimento', attr: 'int', description: 'Educação e cultura.' },
  { id: 'cura', name: 'Cura', attr: 'sab', description: 'Primeiros socorros.' },
  { id: 'diplomacia', name: 'Diplomacia', attr: 'car', description: 'Persuasão e etiqueta.' },
  { id: 'enganacao', name: 'Enganação', attr: 'car', description: 'Mentiras e disfarces.' },
  { id: 'fortitude', name: 'Fortitude', attr: 'con', description: 'Resistência física.' },
  { id: 'furtividade', name: 'Furtividade', attr: 'des', description: 'Esconder-se e silêncio.' },
  { id: 'guerra', name: 'Guerra', attr: 'int', description: 'Tática e estratégia.' },
  { id: 'iniciativa', name: 'Iniciativa', attr: 'des', description: 'Velocidade de reação.' },
  { id: 'intimidacao', name: 'Intimidação', attr: 'car', description: 'Coerção e medo.' },
  { id: 'intuicao', name: 'Intuição', attr: 'sab', description: 'Perceber mentiras.' },
  { id: 'investigacao', name: 'Investigação', attr: 'int', description: 'Procurar pistas.' },
  { id: 'jogatina', name: 'Jogatina', attr: 'car', description: 'Jogos de azar.' },
  { id: 'ladinagem', name: 'Ladinagem', attr: 'des', description: 'Mãos leves e fechaduras.' },
  { id: 'luta', name: 'Luta', attr: 'for', description: 'Combate corpo a corpo.' },
  { id: 'misticismo', name: 'Misticismo', attr: 'int', description: 'Conhecimento arcano.' },
  { id: 'nobreza', name: 'Nobreza', attr: 'int', description: 'Etiqueta e linhagens.' },
  { id: 'oficio', name: 'Ofício', attr: 'int', description: 'Fabricar itens.' },
  { id: 'percepcao', name: 'Percepção', attr: 'sab', description: 'Notar arredores.' },
  { id: 'pilotagem', name: 'Pilotagem', attr: 'des', description: 'Conduzir veículos.' },
  { id: 'pontaria', name: 'Pontaria', attr: 'des', description: 'Ataques à distância.' },
  { id: 'reflexos', name: 'Reflexos', attr: 'des', description: 'Esquiva e agilidade.' },
  { id: 'religiao', name: 'Religião', attr: 'sab', description: 'Conhecimento divino.' },
  { id: 'sobrevivencia', name: 'Sobrevivência', attr: 'sab', description: 'Rastrear e caçar.' },
  { id: 'vontade', name: 'Vontade', attr: 'sab', description: 'Resistência mental.' }
];
